dist: trusty

language: java

jdk:
  - oraclejdk8
  - openjdk8

before_script:
  - cp FHIR-MAPPING/config.properties.example FHIR-MAPPING/config.properties

script: 
  # - gradle -p FHIR-MAPPING build 
  - gradle -p FHIR-MAPPING test --stacktrace --debug

jobs:
  include:      
    - stage: integration
      rvm: 2.4
      before_script:
        - cp FHIR-MAPPING/config.properties.example FHIR-MAPPING/config.properties
        - cd fhir_testing
        - bundle install
      script:
        - cucumber

after_success:
  - bash <(curl -s https://codecov.io/bash)

      

      
