dist: trusty

language: java

jdk:
  - oraclejdk8
  - openjdk8

script: 
  - gradle -p FHIR-MAPPING build 
  - gradle -p FHIR-MAPPING test

jobs:
  include:      
    - stage: integration
      rvm: 2.4
      before_script:
        - cd fhir_testing
        - bundle install
      script:
        - cucumber

after_success:
  - bash <(curl -s https://codecov.io/bash)

      

      
